name: flutter_midi_command_web
description: FlutterMidiCommand for the web.
version: 0.0.1
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterMidiCommandWeb
        fileName: flutter_midi_command_web.dart

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  flutter_midi_command_platform_interface: ^0.3.2
  js: ^0.6.4
  js_bindings: 0.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
